---
name: CI

on: push

jobs:
  deploy:
    name: Deploy to Github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up node # we need node for for semantic release
        uses: actions/setup-node@v2
        with:
          node-version: 14.17
      - name: install semantic-release
        run: npm install semantic-release
      - name: run semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
