---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: prepare context
        id: prepare-context
        env:
          FREECAD_APPIMAGE: 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.2/FreeCAD_0.19-24291-Linux-Conda_glibc2.12-x86_64.AppImage'
          IFCOPENSHELL_ZIP: 'https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-38-v0.6.0-721fe47-linux64.zip'
        run: |
          ./scripts/prepare_docker_context

      - name: build container image
        id: docker-build
        run: |
          docker build --target=dev -t honeybee-ifc:latest-dev .

      - name: run tests
        id: test
        run: |
          docker run --entrypoint=bash honeybee-ifc:latest-dev ./scripts/test

  deploy:
    name: Deploy to Github
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: set up node # we need node for for semantic release
        uses: actions/setup-node@v2
        with:
          node-version: 14.17

      - name: install semantic-release
        run: npm install semantic-release

      - name: run semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

